"""Add generation_metrics table

Revision ID: 3a100be76b28
Revises: 7f132f9eeffb
Create Date: 2026-08-31 05:18:22.245416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '3a100be76b28'
down_revision: Union[str, Sequence[str], None] = '7f132f9eeffb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('call_type', sa.Enum('section_generation', 'review_parse', 'critique', name='call_type'), nullable=False),
    sa.Column('section_type', postgresql.ENUM('overview', 'gameplay_mechanics', 'story_narrative', 'characters', 'world_building', 'progression', 'additional', name='section_type', create_type=False), nullable=True),
    sa.Column('status', sa.Enum('ok', 'invalid', 'rate_limited', 'error', name='generation_status'), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('tokens_total', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_metrics_created_at'), 'generation_metrics', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generation_metrics_created_at'), table_name='generation_metrics')
    op.drop_table('generation_metrics')
    # ### end Alembic commands ###
