"""Add raw_content to reviews

Revision ID: 7f132f9eeffb
Revises: 47076df75f24
Create Date: 2026-08-31 04:49:30.868475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f132f9eeffb'
down_revision: Union[str, Sequence[str], None] = '47076df75f24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('raw_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'raw_content')
    # ### end Alembic commands ###
